server:
  servlet:
    context-path: /
  port: 9080
  compression:
    mime-types:
      - application/json

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5430/dangeous_dragons
    username: dangeous
    password: dragons
    continue-on-error: true

  application:
    name: dangeous-dragons
  jpa:
    open-in-view: false
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          batch_size: 50
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-local.xml
  databaseChangeLog:
    - includeAll:
        path: db/changelog/changes
